---
title: "data.table cheat sheet"
output: html_notebook
---

```{r}
library(data.table)
```


## Create a data.table

```{r}
data.table(a = c(1, 2), b = c("a", "b"))
```

```{r}
dt <- mtcars
setDT(dt)
dt
```

```{r}
dt <- as.data.table(dt)
dt
```


## Subset rows using i

```{r}
dt[1:2,]
```


```{r}
df[mpg > 20,]
```
```{r}
df[mpg %between% c(20, 25),]
```

## Manipulate columns with j

```{r}
dt[, c(2)]
```

```{r}
dt2 <- dt[, .(mpg, cyl)]
dt2
```

```{r}
dt2[, .(x = sum(mpg))]
```


```{r}
dt2[, c := 1 + 2]
dt2
```

```{r}
dt2[mpg == 21.0, d := 1 + 2]
dt2
```
```{r}
dt2[, `:=`(e = 1, f = 2)]
dt2
```

```{r}
dt2[, `:=`(c = NULL, d = NULL, e = NULL, f = NULL)]
dt2
```

```{r}
dt2[, mc := mpg + cyl]
dt2
```
## Group according to by

```{r}
dt2[, .(c = sum(mpg)), by = cyl]
```

```{r}
dt2[, .(c = sum(mpg)), keyby = cyl]  # sorted
```


```{r}
dt2[, c := mean(mpg), by = cyl]
dt2
```
```{r}
dt2[, `:=`(mc = NULL, c = NULL)]
dt2
```

```{r}
dt2[, .SD[1], by = cyl]  # 그룹별 첫번째 줄
```


```{r}
dt2[, .SD[.N], by = cyl]  # 그룹별 마지막 줄
```


## Chaining

```{r}
dt2[, mc := mpg + cyl][, .(s = mean(mc)), by = cyl]
```

## Functions for data.tables

```{r}
setorder(dt2, cyl, -mpg)
dt2
```

```{r}
unique(dt2, by = c("cyl"))
```

```{r}
uniqueN(dt2, by = c("cyl"))
```


```{r}
setnames(dt2, c("mpg", "cyl"), c("MPG", "CYL"))
dt2
```
## Combine data.tables

```{r}

```







